@startuml Phone

!include User.puml 
!include UserManager.puml
!include Brand.puml
!include Client.puml
!include Image.puml 

Class Phone {
    
    - model : string
    - slug : string
    - color : string
    - operator_lock : string
    - screen_size: decimal
    - storage_capacity : string
    - dual_sim : bool
    - memory : string
    - megapixels : int
    - operating_system : string
    - resolution : string
    - network : string
    - manufacturer_reference: string
    - card_reader : bool
    - release_year: int
    - serie : string
    - card_sim : string
    - weight : string
    - height : int
    - width : int
    - depth : int
    - garantee : string
    - description : string
    - created_at : Datetime
    - updated_at : Datetime
}


Client "1"-* User: create <
Brand "1"-* Phone: have <>
Phone "1"-* Image: have <

User - UserManager: exec


@enduml
