@startuml Client

left to right direction

actor "client" as client #Orange

rectangle BileMo {

  usecase "Etre authentifier" as UC1
  usecase "Consulter la liste des téléphones" as UC2
  usecase "Consulter un téléphone" as UC3
  usecase "Ajouter un utilisateur" as UC4
  usecase "Modifier un utilisateur" as UC5
  usecase "Supprimer un utilisateur" as UC6

}

client --> UC1
client --> UC2
client --> UC3
client --> UC4
client --> UC5
client --> UC6

@enduml
