@startuml Client

left to right direction

actor "client" as client #Orange

rectangle BileMo {

  usecase "Se connecter à l'API" as UC1
  usecase "Etre authentifier avec JWT" as UC2
  usecase "Consulter la liste des téléphones" as UC3
  usecase "Consulter un téléphone" as UC4
  usecase "Ajouter un utilisateur" as UC5
  usecase "Modifier un utilisateur" as UC6
  usecase "Supprimer un utilisateur" as UC7

}

client --> UC1
client --> UC2
client --> UC3
client --> UC4
client --> UC5
client --> UC6
client --> UC7

@enduml
