@startuml User

left to right direction

actor "user" as user #SteelBlue

rectangle BileMo {

  usecase "Créer un compte" as UC1
  usecase "Etre authentifier" as UC1
  usecase "Se connecter" as UC2
  usecase "Consulter les téléphones" as UC3
  usecase "Consulter un téléphone" as UC4
  usecase "Ajouter un utilisateur" as UC5
  usecase "Modifier un utilisateur" as UC6
  usecase "Supprimer un utilisateur" as UC7
  usecase "Réinitialiser son mot de passe" as UC8

}

user --> UC1
user --> UC2
user --> UC3
user --> UC4
user --> UC5
user --> UC6
user --> UC7
user --> UC8

@enduml